<a href="https://colab.research.google.com/github/SusantaBanerjee/ML-College/blob/main/Decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import graphviz
import os


In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
dataset = pd.read_csv("drug200.csv")
dataset.iloc[0:1,]


Age Sex    BP Cholesterol  Na_to_K   Drug
0   23   F  HIGH        HIGH   25.355  drugY

Print the first 5 rows of the dataframe.

In [ ]:
dataset.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

Let's observe the shape(Rows, Columns) of the dataframe.

In [ ]:
dataset.shape

(200, 6)

 converting object (character) to float (numeric)

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

dataset.Drug = le.fit_transform(dataset.Drug)
dataset.Drug.unique()#dep variable

array([4, 2, 3, 0, 1])

independent variable

In [ ]:
dataset.Age = le.fit_transform(dataset.Age)
dataset.Sex = le.fit_transform(dataset.Sex)
dataset.BP = le.fit_transform(dataset.BP)
dataset.Cholesterol = le.fit_transform(dataset.Cholesterol)
dataset.Na_to_K = le.fit_transform(dataset.Na_to_K)
dataset.Drug = le.fit_transform(dataset.Drug)


pd.set_option('display.max_columns', None)
show all columns

In [ ]:
dataset.shape#no_of_rows and columns
dataset.Drug.unique()#dependent variable


X = dataset.drop('Drug', axis=1)
Y = dataset['Drug']


gini index method
split the dataset into 70% training and 30% testing

In [ ]:

import random
random.seed(100)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.30,random_state=0)

len(X_train)#X is all ind variables
len(X_test)#X is all ind variables

len(y_train)# y is dep variable
len(y_test)# y is dep variable


from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(random_state=0)#gini default
classifier.fit(X_train, y_train)


DecisionTreeClassifier(random_state=0)

predict the test data

In [ ]:

y_pred = classifier.predict(X_test)


validation of the model

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 5  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  0 18  0]
 [ 0  0  0  0 30]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         4
           3       1.00      1.00      1.00        18
           4       1.00      1.00      1.00        30

    accuracy                           1.00        60
   macro avg       1.00      1.00      1.00        60
weighted avg       1.00      1.00      1.00        60



 Load libraries

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 1.0


In [ ]:
#sensitivity=recall
#specificity = precision
#f1 score ranges from 0 - 1; closer to 1 better the model
#f1 score = 2*((precision*recall)/(precision+recall))

#pruning
####

no_of_folds = [2, 3, 4, 5, 6,7,8,9] 
  
for max_depths in no_of_folds: 

  classifier = DecisionTreeClassifier(max_depth=max_depths)
  classifier.fit(X_train, y_train)

  y_pred = classifier.predict(X_test)


  from sklearn.metrics import classification_report, confusion_matrix
  #print(confusion_matrix(y_test, y_pred))
  #print(classification_report(y_test, y_pred))
  acc = metrics.accuracy_score(y_test, y_pred)
  print("For max depth of ", max_depths, " accuracy is ", acc)

For max depth of  2  accuracy is  0.8833333333333333
For max depth of  3  accuracy is  0.8833333333333333
For max depth of  4  accuracy is  1.0
For max depth of  5  accuracy is  1.0
For max depth of  6  accuracy is  1.0
For max depth of  7  accuracy is  1.0
For max depth of  8  accuracy is  1.0
For max depth of  9  accuracy is  1.0


In [ ]:
## use the max_depth option to prune
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(max_depth=3,random_state=0)#entropy method
classifier.fit(X_train, y_train)
#predict the test data
y_pred = classifier.predict(X_test)

# validation of the model
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 5  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  4  0  0]
 [ 0  0  7 11  0]
 [ 0  0  0  0 30]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         3
           2       0.36      1.00      0.53         4
           3       1.00      0.61      0.76        18
           4       1.00      1.00      1.00        30

    accuracy                           0.88        60
   macro avg       0.87      0.92      0.86        60
weighted avg       0.96      0.88      0.90        60



In [ ]:
# Load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics #Import scikit-learn metrics module for accuracy calculation
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.8833333333333333


In [ ]:
#importance of the variable
importances  = classifier.feature_importances_#read in same order as X

a = pd.DataFrame(list(zip(X.columns, importances)))

a.columns = ["a","b"]#rename the columns
a.sort_values(["b"],ascending=False)

a         b
4      Na_to_K  0.511512
2           BP  0.317198
0          Age  0.171289
1          Sex  0.000000
3  Cholesterol  0.000000